all:
	bison -d sintactico.y && flex lexico.l && gcc *.c -o calculadora -lfl -lm
osx:
	bison -d sintactico.y && flex lexico.l && gcc *.c -o calculadora -ll -lm
linux:
	bison -d sintactico.y && flex lexico.l && gcc *.c -o calculadora -lfl -lm
